### ISSUE TITLE
Saved and Used menu are not  working

### ISSUE THREAD

**Issue by karlcow** [arai-a/ditm#17] opened 2021-06-01 23:27 UTC
1. With Firefox Nightly 90.0a1 (2021-05-29) (64-bit) on macOS 11.4 (20F71)
2. Go to https://www.mozilla.org/en-US/
3. Open developer tools
4. Click on DITM icon
5. Click on Select URL to load (Used)

Expected:
List of URLs

Actual:
Menu is not responsive. 

Notes:

* Same are erasing and installing the addon again
* Same with Firefox Nightly 91.0a1 (2021-05-31) (64-bit)
* Using Version: 1.5.0 Last Updated: June 2, 2021

Browser Console Error:

```
08:24:20.209 TypeError: can't access property "getFullZoomForBrowser", ZoomManager is undefinedSelectParent.jsm:784:1
    receiveMessage resource://gre/actors/SelectParent.jsm:784
    (Async: JSActor query)
    showDropDown resource://gre/actors/SelectChild.jsm:128
    SelectContentHelper resource://gre/actors/SelectChild.jsm:64
    handleEvent resource://gre/actors/SelectChild.jsm:447
```

<img width="776" alt="Capture d’écran 2021-06-02 à 08 25 14" src="https://user-images.githubusercontent.com/505230/120401999-13c57200-c37c-11eb-8187-b4d006212575.png">

```js
         let { ZoomManager } = topBrowsingContext.topChromeWindow;
         SelectParentHelper.populate(
           menulist,
           data.options.options,
           data.options.uniqueStyles,
           data.selectedIndex,
           // We only want to apply the full zoom. The text zoom is already
           // applied in the font-size.
           ZoomManager.getFullZoomForBrowser(browser),
           data.defaultStyle,
           data.style
         );
```

aka `ZoomManager.getFullZoomForBrowser(browser)`

**Comment by arai-a** [comment] 2021-06-02 01:44
Thank you for reporting!

reproduced the issue, and it seems to be reproducible only when the devtools is in the separate window.
I also observed the error for `getFullZoomForBrowser` there.

temporary workaround is to put the devtools in the main browser window (meatball menu -> "Dock to Bottom").

will investigate the issue.

**Comment by arai-a** [comment] 2021-06-02 02:00
regression range:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=d1a5cda117eee6d9671046afb338cb76b3c9baf9&tochange=298c0914b5afdc7c1781913a83039a4c7f6805dd

it's from https://bugzilla.mozilla.org/show_bug.cgi?id=1647727
and the regression is filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1659618

**Comment by arai-a** [comment] 2021-06-03 02:33
Fixed on m-c: https://hg.mozilla.org/mozilla-central/rev/d93dbe2a3c9c
Will be available from Firefox 91 and 91 ESR

**Closed by arai-a** 2021-06-03 02:33 UTC
Labels: blocked by m-c bug, bug
